---
# options for analysis running
run:
  deadline: 20m
  issues-exit-code: 1
  tests: true

# output configuration options
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

# linters that we should / shouldn't run
linters:
  enable-all: true
  disable:
    - golint
    - varcheck
    - ifshort
    - interfacer
    - structcheck
    - exhaustivestruct
    - scopelint
    - deadcode
    - nosnakecase
    - maligned
