cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "Evaluate flake.nix",
  "devShell default [x86_64-linux]",
  "package default [x86_64-linux]",
  "package queued-build-hook [x86_64-linux]"
]
